# Change these first
owner: TIM-JYU # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: TIM
    url: https://tim.jyu.fi
  - name: TIM Email Lists
    url: https://api.timlist.it.jyu.fi/3.1
    expectedStatusCodes:
      - 401

status-website:
  theme: light
  cname: status.tim.education
  logoUrl: https://raw.githubusercontent.com/TIM-JYU/status/master/assets/tim-logo.svg
  name: TIM Status
  introTitle: "TIM (**T**he **I**nteractive **M**aterial) is an open-source cloud-based platform for creating interactive learning documents."
  introMessage: You can view status of the TIM website and its additional services.
  navbar:
    - title: Status
      href: /
    - title: TIM
      href: https://tim.jyu.fi
    - title: Contact us
      href: mailto:tim@jyu.fi
